### ISSUE TITLE
Book key number

### ISSUE THREAD

**Issue by jroedel** [scrollmapper/bible_databases_deuterocanonical#1]
Hi there, thanks for the great work done here. 

I noticed in the bible_databases repository each book has an identifying number in the database, and I'm interested in maintaining these numbers in my own database to maintain compatibility with these repositories. I'm work with Catholic bible texts and since we use many of the books contained in this deuterocanonical repository in our editions, I was wondering if these books also were assigned identifiers by this team. 

Pax!

**Comment by scrollmapper** [comment]
This is a simple Django app, and it would have included many things automatically as books and databases were added via the models in models.py

**Comment by scrollmapper** [comment]
Going to restart this repo. Thanks for commenting.
