### ISSUE TITLE
Update readme.md with details for understanding the symbols within the translation text

### ISSUE THREAD

**Issue by Qara-Penimah** [scrollmapper/bible_databases_deuterocanonical#2]
- ⌈⌈and⌉⌉
- (even)
- ⌈And appear from His camp⌉
- said--Enoch
- In those days ye shall make your names an eternal execration unto all the righteous, b. And
- And all the . . . shall rejoice
- Go to Noah〉
- †four†
- [22:1] And thence I went to another place, and he showed me in the west ⌈another⌉ great and high mountain [and] of hard rock. 
 E 
[22:2] And there was in it †four† hollow places, deep and wide and very smooth. †How† smooth are the hollow places and deep and dark to look at. 
Gg 

What are the meanings of the symbols plus the characters 'E' & 'Gg'?

These were taken from 1-enoch.txt.

**Comment by scrollmapper** [comment]
Good question. 
The original sources were (to the best of my knowledge) auto-ripped using text recognition software. The symbols were used to denote differences between manuscripts in some cases. 
Here is a funny fact: As a fan of the book of Enoch, I've ordered books from amazon (based on the RH Charles version) and discovered they were cheap auto-rips that were made into book form and sold without edits. Quite a puzzle just to read the text, with sentences running together and paragraphs jumbled. Hopefully the issue you point out is all you had in going through the BOE.

**Comment by LeoBlanchette** [comment]
This is fixed now.
